[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "safeincave"
dynamic = ["version"]
description = "A multiphysics finite element simulator for salt cavern"
readme = "README.md"
requires-python = ">=3.10,<3.13"
authors = [{name = "Hermínio T. Honório"}]
maintainers = [
    {name = "SafeInCave Developers"},
]
license = { text = "BSD-3-Clause" }

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
  "numpy==1.26.4",
  "torch==2.4.0",
  "meshio==3.3.1",
  "gmsh>=4.14.0",
  "lxml",
  "pytz",
  "h5py",
  "skops",
  "ruff",
  "scikit-learn>=1.7.2,<2",
  "CoolProp==7.2.0",
  "scipy==1.14.1",
]

[project.optional-dependencies]
docs = [
  "mkdocs",
  "mkdocs-material",
  "pymdown-extensions",
  "mkdocs-caption",
  "mkdocstrings[python]",
]

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools.dynamic]
version = { attr = "safeincave.__version__" }

[tool.setuptools.packages.find]
where = ["."]
include = ["safeincave*"]

[tool.setuptools.package-data]
"safeincave" = ["app/assets/*.png", "model_h.skops"]

[project.urls]
Repository = "https://github.com/ADMIRE-Public/SafeInCave"