"""Auto-generated by safeincave.Transpiler from 'case.yaml'.
Includes material.yaml.

This script is standalone: it only uses the public safeincave API and
can be edited and run like any hand-written case script.
"""
import torch as to

import safeincave as sf
import safeincave.BC.Momentum as momBC


def _check_fields(eq, field_names):
    """Fail on an unknown output field before the simulation starts."""
    missing = [name for name in field_names if not hasattr(eq, name)]
    if missing:
        available = sorted(
            name for name, value in vars(eq).items() if hasattr(value, "function_space")
        )
        raise AttributeError(
            f"{type(eq).__name__} has no field(s) {missing}. "
            f"Available fields: {available}"
        )


def main():
    # --- Grid ---
    grid = sf.GridHandlerGMSH(geometry_name='geom', grid_folder='../../../grids/cube')

    # --- Equations ---
    mom_eq = sf.LinearMomentum(grid, theta=0.5)

    # --- Material ---
    mat = sf.Material(grid.n_elems)
    mat.set_density(2000.0 * to.ones(grid.n_elems, dtype=to.float64))
    elem_0 = sf.Spring(
        name='spring',
        E=102000000000.0 * to.ones(grid.n_elems, dtype=to.float64),
        nu=0.3 * to.ones(grid.n_elems, dtype=to.float64),
    )
    mat.add_to_elastic(elem_0)
    elem_1 = sf.Viscoelastic(
        name='kelvin',
        eta=10500000000000.0 * to.ones(grid.n_elems, dtype=to.float64),
        E=10000000000.0 * to.ones(grid.n_elems, dtype=to.float64),
        nu=0.32 * to.ones(grid.n_elems, dtype=to.float64),
    )
    mat.add_to_non_elastic(elem_1)
    elem_2 = sf.DislocationCreep(
        name='creep',
        A=1.9e-20 * to.ones(grid.n_elems, dtype=to.float64),
        Q=51600.0 * to.ones(grid.n_elems, dtype=to.float64),
        n=3.0 * to.ones(grid.n_elems, dtype=to.float64),
    )
    mat.add_to_non_elastic(elem_2)
    elem_3 = sf.ViscoplasticDesai(
        name='desai',
        mu_1=5.366585700985981e-11 * to.ones(grid.n_elems, dtype=to.float64),
        N_1=3.1 * to.ones(grid.n_elems, dtype=to.float64),
        a_1=1.965018496922832e-05 * to.ones(grid.n_elems, dtype=to.float64),
        eta=0.8275682807874163 * to.ones(grid.n_elems, dtype=to.float64),
        n=3.0 * to.ones(grid.n_elems, dtype=to.float64),
        beta_1=0.0048 * to.ones(grid.n_elems, dtype=to.float64),
        beta=0.995 * to.ones(grid.n_elems, dtype=to.float64),
        m=-0.5 * to.ones(grid.n_elems, dtype=to.float64),
        gamma=0.095 * to.ones(grid.n_elems, dtype=to.float64),
        sigma_t=5.0 * to.ones(grid.n_elems, dtype=to.float64),
        alpha_0=0.0022 * to.ones(grid.n_elems, dtype=to.float64),
    )
    mat.add_to_non_elastic(elem_3)
    mom_eq.set_material(mat)

    # --- Initial state ---
    mom_eq.build_body_force([0.0, 0.0, 0.0])
    T0_elems = 293.0 * to.ones(grid.n_elems, dtype=to.float64)
    mom_eq.set_T0(T0_elems)
    mom_eq.set_T(T0_elems)

    # ===== Stage 0: triaxial =====
    t_control = sf.TimeController(
        dt=0.5,
        initial_time=0.0,
        final_time=24,
        time_unit='hour',
    )

    bc_handler_mom = momBC.BcHandler()
    bc_0 = momBC.DirichletBC(
        boundary_name='WEST',
        component=0,
        values=[0.0, 0.0],
        time_values=[0.0, 86400.0],
    )
    bc_handler_mom.add_boundary_condition(bc_0)
    bc_1 = momBC.DirichletBC(
        boundary_name='SOUTH',
        component=1,
        values=[0.0, 0.0],
        time_values=[0.0, 86400.0],
    )
    bc_handler_mom.add_boundary_condition(bc_1)
    bc_2 = momBC.DirichletBC(
        boundary_name='BOTTOM',
        component=2,
        values=[0.0, 0.0],
        time_values=[0.0, 86400.0],
    )
    bc_handler_mom.add_boundary_condition(bc_2)
    bc_3 = momBC.NeumannBC(
        boundary_name='EAST',
        direction=2,
        density=0.0,
        ref_pos=0.0,
        g=0.0,
        values=[4000000.0, 4000000.0],
        time_values=[0.0, 86400.0],
    )
    bc_handler_mom.add_boundary_condition(bc_3)
    bc_4 = momBC.NeumannBC(
        boundary_name='NORTH',
        direction=2,
        density=0.0,
        ref_pos=0.0,
        g=0.0,
        values=[4000000.0, 4000000.0],
        time_values=[0.0, 86400.0],
    )
    bc_handler_mom.add_boundary_condition(bc_4)
    bc_5 = momBC.NeumannBC(
        boundary_name='TOP',
        direction=2,
        density=0.0,
        ref_pos=0.0,
        g=0.0,
        values=[4100000.0, 16000000.0, 16000000.0, 6000000.0, 6000000.0],
        time_values=[0.0, 7200.0, 50400.0, 57600.0, 86400.0],
    )
    bc_handler_mom.add_boundary_condition(bc_5)
    mom_eq.set_boundary_conditions(bc_handler_mom)

    out_0 = sf.SaveFields(mom_eq, output_format='xdmf')
    out_0.set_output_folder('output/case_0/yaml')
    _check_fields(mom_eq, ['u', 'eps_tot', 'sig'])
    out_0.add_output_field('u', 'Displacement (m)')
    out_0.add_output_field('eps_tot', 'Total strain (-)')
    out_0.add_output_field('sig', 'Stress (Pa)')

    outputs = [out_0]
    sim = sf.Simulator_M(
        eq_mom=mom_eq,
        t_control=t_control,
        outputs=outputs,
        compute_elastic_response=True,
    )
    sim.run()


if __name__ == "__main__":
    main()
