# Copyright (c) 2026, The SafeInCave Developers
#
# SPDX-License-Identifier: BSD-3-Clause

"""YAML case definitions for SafeInCave (transpiled to Python).

A YAML case file is converted into a standalone Python script that only uses
the public safeincave API, and that script is what runs — there is no second,
object-building code path, so ``sic run case.yaml`` and ``sic convert``
cannot diverge.

The YAML schema is reflection-driven: ``type:`` values are real class names
and the keys of each block are the real constructor parameter names, checked
against ``inspect.signature`` (see :mod:`.registry` and :mod:`.signatures`).
Classes added through the extensions overlay or the constitutive-model
auto-discovery become legal YAML keywords automatically.

Usage::

    sic run case.yaml            # transpile + run
    sic convert case.yaml        # export the generated Python script
"""

from __future__ import annotations

import runpy
import sys
import tempfile
from pathlib import Path

from .codegen import GENERATED_MARKER, generate
from .errors import TranspileError
from .model import parse

__all__ = ["transpile", "convert", "run_yaml", "TranspileError"]


def transpile(yaml_path) -> str:
    """Convert a YAML case file into Python source code."""
    return generate(parse(yaml_path))


def convert(yaml_path, out_path=None, force: bool = False) -> Path:
    """Write the generated Python script next to the YAML file (or to ``out_path``).

    Refuses to overwrite a file that was not itself generated by the
    transpiler, unless ``force`` is given.
    """
    yaml_path = Path(yaml_path)
    source = transpile(yaml_path)
    out_path = Path(out_path) if out_path else yaml_path.with_suffix(".py")
    if out_path.exists() and not force:
        first_lines = out_path.read_text().splitlines()[:2]
        if not any(GENERATED_MARKER in line for line in first_lines):
            raise TranspileError(
                f"{out_path} exists and is not a generated script; "
                f"use -o to pick another name or --force to overwrite."
            )
    out_path.write_text(source)
    return out_path


def run_yaml(yaml_path, script_args=()) -> None:
    """Transpile a YAML case file and run the generated script.

    The script is written to a temporary directory and executed in-process
    with the YAML file's directory as working directory, so relative paths in
    the YAML (mesh folder, output folders) resolve exactly as they would for
    a hand-written ``main.py`` living next to it.
    """
    import os

    yaml_path = Path(yaml_path).resolve()
    source = transpile(yaml_path)

    tmp_dir = Path(tempfile.mkdtemp(prefix="sic_yaml_"))
    script_path = tmp_dir / f"{yaml_path.stem}_generated.py"
    script_path.write_text(source)

    old_cwd = os.getcwd()
    old_argv = sys.argv
    os.chdir(yaml_path.parent)
    sys.argv = [str(script_path), *script_args]
    try:
        runpy.run_path(str(script_path), run_name="__main__")
    except Exception:
        print(f"Error while running generated script: {script_path}", file=sys.stderr)
        raise
    finally:
        os.chdir(old_cwd)
        sys.argv = old_argv
