# Copyright (c) 2026, The SafeInCave Developers
#
# SPDX-License-Identifier: BSD-3-Clause

"""Emit a standalone Python case script from a validated :class:`CaseModel`.

The generated script mirrors the structure of the hand-written example
scripts (grid → equations → material → initial state → per-stage BCs,
outputs, simulator) and depends only on the public safeincave API, so it can
be exported with ``sic y2p`` and edited like any other case script.
"""

from __future__ import annotations

from . import registry, signatures
from .model import CaseModel, ObjectSpec, RawCode, StageSpec

GENERATED_MARKER = "Auto-generated by safeincave.Transpiler"

_MAX_LINE = 88

_EQ_VARS = {"momentum": "mom_eq", "heat": "heat_eq"}

_REGION_TENSOR_HELPER = '''\
def _region_tensor(grid, values, context):
    """Per-region {region: value} map -> per-element tensor."""
    tensor = to.zeros(grid.n_elems, dtype=to.float64)
    for region, value in values.items():
        if region not in grid.region_indices:
            raise KeyError(
                f"{context}: unknown region '{region}'. "
                f"Available regions: {sorted(grid.region_indices)}"
            )
        tensor[grid.region_indices[region]] = float(value)
    return tensor
'''

# Field names only exist once the equation is built, so they are checked here
# rather than at transpile time - but before the first solve, so a typo fails
# immediately instead of after the simulation has already run a step.
_OUTPUT_FIELD_HELPER = '''\
def _check_fields(eq, field_names):
    """Fail on an unknown output field before the simulation starts."""
    missing = [name for name in field_names if not hasattr(eq, name)]
    if missing:
        available = sorted(
            name for name, value in vars(eq).items() if hasattr(value, "function_space")
        )
        raise AttributeError(
            f"{type(eq).__name__} has no field(s) {missing}. "
            f"Available fields: {available}"
        )
'''


class CodeWriter:
    def __init__(self):
        self.lines = []
        self.indent = 0

    def line(self, text: str = "") -> None:
        self.lines.append("    " * self.indent + text if text else "")

    def call(self, target: str, callee: str, args: list) -> None:
        """Emit ``target = callee(args...)``, wrapping when too long.

        ``args`` is a list of already-rendered argument strings.
        """
        prefix = f"{target} = " if target else ""
        one_line = f"{prefix}{callee}({', '.join(args)})"
        if len("    " * self.indent + one_line) <= _MAX_LINE:
            self.line(one_line)
            return
        self.line(f"{prefix}{callee}(")
        self.indent += 1
        for arg in args:
            self.line(f"{arg},")
        self.indent -= 1
        self.line(")")

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"


def _fmt(value) -> str:
    """Render a plain YAML value as a Python literal."""
    if isinstance(value, RawCode):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_fmt(v) for v in value) + "]"
    return repr(value)


def _tensor_expr(value, context: str) -> str:
    """Render a scalar or {region: value} map as a per-element tensor expression."""
    if isinstance(value, dict):
        return f"_region_tensor(grid, {_fmt_region_map(value)}, {context!r})"
    return f"{value!r} * to.ones(grid.n_elems, dtype=to.float64)"


def _fmt_region_map(values: dict) -> str:
    entries = ", ".join(f"{region!r}: {value!r}" for region, value in values.items())
    return "{" + entries + "}"


def _kwargs_args(spec: ObjectSpec, context: str) -> list:
    """Rendered ``key=value`` strings for one ObjectSpec, tensors included."""
    args = []
    for key, value in spec.kwargs.items():
        args.append(f"{key}={_fmt(value)}")
    for key, value in spec.tensor_kwargs.items():
        args.append(f"{key}={_tensor_expr(value, f'{context}.{key}')}")
    return args


def _callee(spec: ObjectSpec) -> str:
    return registry.SECTIONS[spec.section].prefix + spec.type_name


def _included_files(model: CaseModel) -> list:
    """Included files, relative to the root case file, in load order."""
    root_dir = model.source.resolve().parent
    included = []
    for source in model.sources[1:]:
        try:
            included.append(source.relative_to(root_dir).as_posix())
        except ValueError:
            included.append(str(source))
    return included


def _uses_region_maps(model: CaseModel) -> bool:
    if any(isinstance(v, dict) for v in model.material.properties.values()):
        return True
    for group in ("elastic", "non_elastic", "thermoelastic"):
        for elem in getattr(model.material, group):
            if any(isinstance(v, dict) for v in elem.tensor_kwargs.values()):
                return True
    return False


def generate(model: CaseModel) -> str:
    w = CodeWriter()

    # ---- header & imports
    w.line(f'"""{GENERATED_MARKER} from {model.source.name!r}.')
    for included in _included_files(model):
        w.line(f"Includes {included}.")
    w.line("")
    w.line("This script is standalone: it only uses the public safeincave API and")
    w.line("can be edited and run like any hand-written case script.")
    w.line('"""')
    w.line("import torch as to")
    w.line("")
    w.line("import safeincave as sf")
    if any("momentum" in stage.bcs for stage in model.stages):
        w.line("import safeincave.BC.Momentum as momBC")
    if any("heat" in stage.bcs for stage in model.stages):
        w.line("import safeincave.BC.Heat as heatBC")
    w.line("")
    w.line("")
    helpers = [_OUTPUT_FIELD_HELPER]
    if _uses_region_maps(model):
        helpers.insert(0, _REGION_TENSOR_HELPER)
    for helper in helpers:
        for line in helper.splitlines():
            w.line(line)
        w.line("")
        w.line("")

    w.line("def main():")
    w.indent += 1

    # ---- grid
    w.line("# --- Grid ---")
    w.call("grid", _callee(model.grid), _kwargs_args(model.grid, "grid"))
    w.line("")

    # ---- equations
    w.line("# --- Equations ---")
    for eq_name, eq_spec in model.equations.items():
        w.call(_EQ_VARS[eq_name], _callee(eq_spec),
               ["grid"] + _kwargs_args(eq_spec, f"equations.{eq_name}"))
    w.line("")

    # ---- material
    w.line("# --- Material ---")
    if model.material.name:
        w.line(f"# {model.material.name}")
    w.line("mat = sf.Material(grid.n_elems)")
    for prop, value in model.material.properties.items():
        w.call("", f"mat.set_{prop}", [_tensor_expr(value, f"material.{prop}")])
    elem_count = 0
    for group in ("elastic", "non_elastic", "thermoelastic"):
        for elem in getattr(model.material, group):
            var = f"elem_{elem_count}"
            context = f"material.{group}.{elem.type_name}"
            w.call(var, _callee(elem), _kwargs_args(elem, context))
            w.call("", f"mat.add_to_{group}", [var])
            elem_count += 1
    for eq_name in model.equations:
        w.line(f"{_EQ_VARS[eq_name]}.set_material(mat)")
    w.line("")

    # ---- initial state
    w.line("# --- Initial state ---")
    if "momentum" in model.equations:
        w.call("", "mom_eq.build_body_force", [_fmt(model.body_force)])
        w.line(f"T0_elems = {model.initial_temperature!r} * to.ones(grid.n_elems, dtype=to.float64)")
        w.line("mom_eq.set_T0(T0_elems)")
        w.line("mom_eq.set_T(T0_elems)")
    if "heat" in model.equations:
        w.line(f"T0_nodes = {model.initial_temperature!r} * to.ones(heat_eq.n_nodes, dtype=to.float64)")
        w.line("heat_eq.set_initial_T(T0_nodes)")
    w.line("")

    # ---- stages
    for index, stage in enumerate(model.stages):
        _generate_stage(w, model, stage, index)

    w.indent -= 1
    w.line("")
    w.line('if __name__ == "__main__":')
    w.line("    main()")
    return w.text()


def _generate_stage(w: CodeWriter, model: CaseModel, stage: StageSpec, index: int) -> None:
    context = f"stages[{index}]"
    w.line(f"# ===== Stage {index}: {stage.name} =====")
    w.call("t_control", _callee(stage.time), _kwargs_args(stage.time, f"{context}.time"))
    w.line("")

    # boundary conditions: one fresh handler per equation, every stage
    handlers = {"momentum": "bc_handler_mom", "heat": "bc_handler_heat"}
    for eq_name, bcs in stage.bcs.items():
        handler = handlers[eq_name]
        prefix = registry.SECTIONS[f"bcs.{eq_name}"].prefix
        w.line(f"{handler} = {prefix}BcHandler()")
        for i, bc in enumerate(bcs):
            var = f"bc_{i}"
            w.call(var, _callee(bc), _kwargs_args(bc, f"{context}.bcs.{eq_name}[{i}]"))
            w.line(f"{handler}.add_boundary_condition({var})")
        w.line(f"{_EQ_VARS[eq_name]}.set_boundary_conditions({handler})")
        w.line("")

    # caverns
    if stage.caverns:
        w.line("cavern_handler = sf.Cavern.CavernHandler()")
        for i, cavern in enumerate(stage.caverns):
            var = f"cavern_{i}"
            args = ["grid=grid"] + _kwargs_args(cavern, f"{context}.caverns[{i}]")
            if "grid" not in signatures.init_parameters(cavern.cls):
                args = args[1:]
            w.call(var, _callee(cavern), args)
            w.line(f"cavern_handler.add_cavern({var})")
        w.line(f"cavern_handler.set_output_folder({stage.outputs[0].folder!r})")
        w.line("")

    # outputs
    outputs_vars = []
    for i, out in enumerate(stage.outputs):
        var = f"out_{i}"
        outputs_vars.append(var)
        w.call(var, "sf.SaveFields",
               [_EQ_VARS[out.equation], f"output_format={out.output_format!r}"])
        w.line(f"{var}.set_output_folder({out.folder!r})")
        w.call("", "_check_fields",
               [_EQ_VARS[out.equation], _fmt(list(out.fields))])
        for field_name, label in out.fields.items():
            w.line(f"{var}.add_output_field({field_name!r}, {label!r})")
        w.line("")
    w.line(f"outputs = [{', '.join(outputs_vars)}]")

    # live extraction profiles: one logger each, fanned out through a
    # CompositeLogger when a step declares more than one (the simulators
    # take a single `simulation_logger`).
    live = [e for e in stage.extracts if e.while_simulating]
    for i, extract in enumerate(live):
        var = "logger" if len(live) == 1 else f"logger_{i}"
        w.call(var, _callee(extract.logger),
               _kwargs_args(extract.logger, f"{context}.outputs.{extract.name}"))
    if len(live) > 1:
        w.line(f"logger = sf.CompositeLogger([{', '.join(f'logger_{i}' for i in range(len(live)))}])")

    # simulator: wire objects onto the parameters the class actually declares
    wired = {
        "eq_mom": _EQ_VARS.get("momentum") if "momentum" in model.equations else None,
        "eq_heat": _EQ_VARS.get("heat") if "heat" in model.equations else None,
        "t_control": "t_control",
        "outputs": "outputs",
        "caverns": "cavern_handler" if stage.caverns else None,
        "simulation_logger": "logger" if live else None,
    }
    sim_params = signatures.init_parameters(stage.simulator.cls)
    args = [
        f"{param}={var}"
        for param, var in wired.items()
        if var is not None and param in sim_params
    ]
    args += _kwargs_args(stage.simulator, f"{context}.simulator")
    w.call("sim", _callee(stage.simulator), args)
    w.line("sim.run()")
    w.line("")

    # post-run extraction profiles: read the fields just written back out
    folder = stage.outputs[0].folder
    for extract in stage.extracts:
        if extract.while_simulating:
            continue
        if extract.kind == "extract_fixed_point":
            w.call("", "sf.extract_point",
                   [_fmt(folder), _fmt(extract.points[0]),
                    _fmt(list(extract.variables)), f"name={extract.name!r}"])
        else:
            w.call("", "sf.extract_variable",
                   [_fmt(folder), _fmt([list(p) for p in extract.points]),
                    _fmt(extract.variables[0]), f"name={extract.name!r}"])
    if any(not e.while_simulating for e in stage.extracts):
        w.line("")
